version: "3"
services:
  apache:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_APACHE}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${APACHE_HOST_HTTP_PORT}:80'
volumes: {}